apiVersion: v1
kind: Pod
metadata:
  name: secret-nautilus
  labels:
    run: secret-nautilus
spec:
  volumes: 
  - name: secret-volume
    secret:
      secretName: ecommerce
  containers:
  - image: fedora:latest
    name: secret-container-nautilus
    command: ["sleep", "3600"] 
    volumeMounts: 
    - name: secret-volume
      mountPath: /opt/games